# Specify the absolute path for the .env file containing the sections.
sections = "C:/cheroshared_files/sections.env"

# Specify the absolute path of the directory where the database files will live in.
db_dir = "C:/cheroapi_files/db"

[grpc_config]
bind_address = "localhost:50051"